#Actual independent observation
#Sun Oct 04 21:06:28 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=uncertain-geometry
required-chains=semantic,standards,syntax
input-sha256=4d5e7cdd98e6e4df4ce46bc53cdc38dedf347c89a1cafc4a8931655733a9eb3c
profile=T13-text-logical-structure
syntax=pass
visual=not-required
retained-files-sha256=6904782a81393be787b4310811665f47608c4880c21dae072bfcf49cf40360e0
execution-profile=HARDENED_WORKER
