#Actual T12 observation
#Fri Sep 11 09:55:16 UTC 2026
receipt.0.target=merged
receipt.0.pdf-sha256=e44ed17a7ca6fea39d894ac9b41ee78ba46a8cdc9bcbe6a3d1a6936138929b9e
receipt.0.status=COMMITTED
receipt.0.partial-output-possible=false
receipt.0.path=/workspace/capabilities/evidence/foundation/T74-r1-annotations/jdk8-in_process/observations/native-merged/annotations.pdf
execution-profile-source=workflow-outcome
execution-profile=IN_PROCESS
receipt-count=1
