#Actual T12 observation
#Fri Sep 11 09:55:16 UTC 2026
receipt.0.target=flattened
receipt.0.pdf-sha256=51375075bad9815dada7d9e72c3cad1115ddc28f26f9a6b20bb77ab0f351d163
receipt.0.status=COMMITTED
receipt.0.partial-output-possible=false
receipt.0.path=/workspace/capabilities/evidence/foundation/T74-r1-annotations/jdk8-in_process/observations/native-flattened/annotations.pdf
execution-profile-source=workflow-outcome
execution-profile=IN_PROCESS
receipt-count=1
