#Actual independent observation
#Wed Sep 30 10:55:39 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=nested-split-type3
required-chains=semantic,standards,syntax,visual
input-sha256=9eb365ec07fac866952b22949a7debb242ebbdb46d3150b420348b59a624f009
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=84efc16a53b43c63d742e4bb3e49f782c53b988dda9af1abb3b41886965d485f
execution-profile=IN_PROCESS
