facade-execution-profile=IN_PROCESS
native-execution-profile=IN_PROCESS
phase=certification
profile=T32-password-embedded-files-only
retained-files-sha256=7868b1b685204b01981a2869f73ef7a0ca19f5ff4ef32ccac518ab9a1b40e6e8
semantic=pass
standards=pass
syntax=pass
visual=pass
