#Actual T11 observation
#Thu Sep 10 18:44:53 UTC 2026
external-file.unmutated=pass
inert-xinclude.pdf-sha256=e75d9eb3caf0c052ca205bfffe3c8ccc96142ed900279fd8d1b6a28a8a07ea81
observer.file-attempts=1
external-file.file-accesses=0
external-file.code=COMMAND_REJECTED
observer.network-attempts=1
external-network.code=COMMAND_REJECTED
external-file.pdf-sha256=b0f33b4b5a4ba5cf7ebfa3f381d2d14f159440d7b49fe8ee594a9ae8a39f4a4c
external-network.pdf-sha256=0fc6ac07c30359ea0e4778a137893a13eaeda5b51748818c07dbf4eec675a340
malformed.unmutated=pass
external-file.network-accesses=0
external-network.network-accesses=0
external-network.unmutated=pass
malformed.pdf-sha256=c012a4fcabb7642704374a0ac75ef0cc5f94a79ca32ff4c3a93615c593a750a6
result=pass
inert-xinclude.exact=pass
api=native
inert-xinclude.reopened=pass
malformed.reopened=pass
external-network.reopened=pass
external-file.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
external-network.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
malformed.network-accesses=0
malformed.file-accesses=0
inert-xinclude.network-accesses=0
inert-xinclude.file-accesses=0
external-network.file-accesses=0
malformed.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
execution-profile=IN_PROCESS
inert-xinclude.accepted=pass
malformed.code=COMMAND_REJECTED
external-file.reopened=pass
