#Actual T11 observation
#Sun Oct 04 18:41:26 UTC 2026
result=pass
native-execution-profile=IN_PROCESS
native=pass
facade-execution-profile=IN_PROCESS
profile=T11-metadata-outlines-destinations-attachments
facade=pass
signed=pass
