#Actual independent observation
#Sun Sep 13 18:21:46 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=nested-split-type3
required-chains=semantic,standards,syntax,visual
input-sha256=9eb365ec07fac866952b22949a7debb242ebbdb46d3150b420348b59a624f009
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=6ec46a43de386720e3855255cf84d6d7ad598fc44c9e5a4843d68f5cdb4496e2
execution-profile=IN_PROCESS
