#Actual independent observation
#Tue Sep 29 16:43:23 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=nested-split-type3
required-chains=semantic,standards,syntax,visual
input-sha256=9eb365ec07fac866952b22949a7debb242ebbdb46d3150b420348b59a624f009
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=bdebbff6f0d882e528be48f486b2c3c4229f1d9b219685fc27209d816649d959
execution-profile=IN_PROCESS
