facade-execution-profile=IN_PROCESS
native-execution-profile=IN_PROCESS
phase=certification
profile=T32-password-embedded-files-only
retained-files-sha256=0cd157579cf7f54961f927f0b349b8e3a9cc8fac764b975dd81229a21df166dc
semantic=pass
standards=pass
syntax=pass
visual=pass
