#Actual T11 observation
#Thu Sep 10 18:56:16 UTC 2026
result=pass
native-execution-profile=HARDENED_WORKER
native=pass
facade-execution-profile=IN_PROCESS
profile=T11-metadata-outlines-destinations-attachments
facade=pass
signed=pass
