#Actual independent observation
#Fri Oct 02 04:33:50 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=nested-split-type3
required-chains=semantic,standards,syntax,visual
input-sha256=9eb365ec07fac866952b22949a7debb242ebbdb46d3150b420348b59a624f009
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=0055e1dcf336899335fc897ecb704646a28020f8f784d14c2a4632a9e62d8835
execution-profile=IN_PROCESS
