<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>net.zerocloud</groupId>
    <artifactId>pdf-parent</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>pdf-migration-itext7-preview</artifactId>
  <packaging>jar</packaging>

  <name>Folio PDF by ZeroCloud - Preview iText 7 Migration Facade</name>
  <description>The mutually exclusive Migration Facade containing stable and experimental mappings.</description>

  <dependencies>
    <dependency>
      <groupId>net.zerocloud</groupId>
      <artifactId>pdf-document</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
      <resource>
        <directory>${project.basedir}/..</directory>
        <targetPath>META-INF</targetPath>
        <includes>
          <include>LICENSE</include>
          <include>NOTICE</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifestEntries>
              <Automatic-Module-Name>net.zerocloud.pdf.migration.itext7.preview</Automatic-Module-Name>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <systemPropertyVariables>
            <artifactPath>${project.build.directory}/${project.build.finalName}.jar</artifactPath>
            <documentArtifactPath>${maven.multiModuleProjectDirectory}/pdf-document/target/pdf-document-${project.version}.jar</documentArtifactPath>
            <stableArtifactPath>${maven.multiModuleProjectDirectory}/pdf-migration-itext7/target/pdf-migration-itext7-${project.version}.jar</stableArtifactPath>
            <testClassesPath>${project.build.testOutputDirectory}</testClassesPath>
            <repositoryRoot>${maven.multiModuleProjectDirectory}</repositoryRoot>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
