#Actual T11 observation
#Thu Sep 10 10:43:18 UTC 2026
semantic=pass
page.1.visual=pass
input-sha256=7aacebad03c7edd38067efdeddee54473b8321aba9fa1aabe9e354338f30facb
page.2.visual=pass
profile=T11-metadata-outlines-destinations-attachments
standards-rule-count=170
semantic-scope=frozen-corpus
standards=pass
syntax=pass
visual=pass
page-count=2
execution-profile=IN_PROCESS
