#Actual independent observation
#Tue Sep 29 17:11:28 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=nested-split-type3
required-chains=semantic,standards,syntax,visual
input-sha256=9eb365ec07fac866952b22949a7debb242ebbdb46d3150b420348b59a624f009
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=b90627eed39773e2a5167a3eb5f4195453676dcf9ba9e382cd5daae0a5ad9ebd
execution-profile=IN_PROCESS
