#Actual independent observation
#Tue Sep 29 00:31:27 UTC 2026
execution-profile=IN_PROCESS
input-sha256=5ee1ba455b80d804eb3245ae57736cd1bcf70c4fbb980d173d8b573ffe4950d5
product=embedded-font-inheritance
profile=T13-text-logical-structure
qualified-standard-rule-count=376
required-chains=semantic,standards,syntax
retained-files-sha256=e49239125bf4fd655ecf65a6875e593f985ae3ac906ff7d9caada9a355254317
semantic=pass
standards=pass
syntax=pass
visual=not-required
