#Actual independent observation
#Tue Oct 06 09:39:14 UTC 2026
visual=pass
standards=pass
required-chains=semantic,standards,syntax,visual
profile=T13-text-logical-structure
input-sha256=42739ab6a69bad744268186e2c51969df0378b78e2a8be228b88cef3025438a2
syntax=pass
execution-profile=IN_PROCESS
retained-files-sha256=fbdddb4d6f38602c1b0e847293456d9522a205f21326e769a9387f42b1f63aed
qualified-standard-rule-count=376
semantic=pass
product=embedded-font-kinds
