#Actual T11 observation
#Fri Sep 11 12:37:29 UTC 2026
phase=certification
native-execution-profile=IN_PROCESS
facade-execution-profile=IN_PROCESS
profile=T11-metadata-outlines-destinations-attachments
