#Actual independent observation
#Wed Sep 30 12:10:32 UTC 2026
execution-profile=IN_PROCESS
input-sha256=5ee1ba455b80d804eb3245ae57736cd1bcf70c4fbb980d173d8b573ffe4950d5
product=embedded-font-inheritance
profile=T13-text-logical-structure
qualified-standard-rule-count=376
required-chains=semantic,standards,syntax
retained-files-sha256=99af2446351fe4ce2db4f2d593c64dc939e23812353f69a1f8d09314319f3fbe
semantic=pass
standards=pass
syntax=pass
visual=not-required
