#Actual independent observation
#Sun Oct 04 20:53:10 UTC 2026
form-position=fail
object-reference=fail
semantic=fail
font-width=fail
parent-tree=fail
profile=T13-text-logical-structure
contents-order=fail
empty-replacement=fail
alternate=fail
language=fail
positive=pass
positive.marked-structure=pass
native-execution-profile=IN_PROCESS
control-count=12
role-target=fail
namespace-reference=fail
positive.nested-split-type3=pass
positive.embedded-font-kinds=pass
positive.embedded-font-inheritance=pass
replacement=fail
mcr=fail
retained-files-sha256=f3f9f1183937e8160698aac441b48fba30c92dbe6876ad7d3b263ae1b99946a2
positive.uncertain-geometry=pass
