package net.zerocloud.pdf.tools.inventory;

import java.io.File;
import java.util.List;
import java.util.Map;

final class FoundationMarkdown {
    static final String OUTPUT = "docs/generated/foundation-readiness.md";

    private FoundationMarkdown() {
    }

    static String generate(FoundationReadiness readiness) {
        FoundationInventory foundation = readiness.foundation;
        String repositoryPrefix = foundation.inventory.repositoryRoot.toString() + File.separator;
        StringBuilder text = new StringBuilder("<!-- Generated by ./scripts/inventory generate. Do not edit. -->\n\n");
        text.append("# Foundation ").append(foundation.release).append(" release readiness\n\n");
        text.append("**").append(readiness.ready() ? "READY" : "NOT READY").append("**. ");
        text.append("Run `./scripts/inventory readiness` for every missing obligation and identity diagnostic. ");
        text.append("Inventory validity is separate from release readiness; regular `verify` checks the current contract without certifying it.\n\n");
        text.append("Authorities: [obligations](../../").append(foundation.path)
                .append("), [source requirements](../../").append(foundation.requirementsPath)
                .append("), [environment profiles](../../").append(foundation.environmentsPath)
                .append("), [retained evidence](../../").append(foundation.evidencePath).append(").\n\n");
        text.append("Only actually exercised Ubuntu 24.04 / Linux x86-64 environments with JDK 8, 11, 17 and 21 are required. ");
        text.append("**Windows x86-64 and macOS x86-64/arm64 are uncertified and are not required release gates for Foundation 0.1.0.** ");
        text.append("[ADR-0040](../../").append(foundation.decision)
                .append(") supersedes only ADR-0026's platform requirement for this version. ");
        text.append("All other Foundation requirements remain mandatory. Matching architecture names or JDK majors never extend certification.\n\n");
        text.append("## Required environment identities\n\n");
        for (FoundationInventory.Environment environment : foundation.environments.values()) {
            text.append("### ").append(code(environment.id)).append("\n\n");
            for (Map.Entry<String, Object> field : environment.identity.entrySet()) {
                text.append("- ").append(field.getKey()).append(": ").append(code(field.getValue())).append('\n');
            }
            text.append('\n');
        }
        text.append("Each certification additionally retains the observed host kernel, execution profile/configuration, native helper/loaded-engine/installation hashes and producer tool versions/hashes. ");
        text.append("An immutable profile declaration is not execution evidence. The evidence must match the actual candidate and current contract.\n\n");
        text.append("## Release-wide findings\n\n");
        if (readiness.global.isEmpty()) {
            text.append("Candidate and environment evidence identities satisfy the declared integrity checks.\n\n");
        } else {
            for (String error : readiness.global) {
                text.append("- ").append(escape(error.replace(repositoryPrefix, ""))).append('\n');
            }
            text.append('\n');
        }
        text.append("## Required obligations\n\n");
        text.append("A missing capability, required behavior, compatible dependency, independent evidence chain, exact environment or Stable Facade mapping blocks release. ");
        text.append("Existing Facade exclusions describe unfinished coverage; they cannot waive these required mappings. ");
        text.append("Only explicitly reasoned project controls are Native Interface only.\n\n");
        text.append("| Obligation | Capability or subcapability | Slice | Status |\n| --- | --- | --- | --- |\n");
        for (FoundationInventory.Obligation obligation : foundation.obligations.values()) {
            text.append("| [").append(code(obligation.id)).append("](#").append(obligation.id).append(") | ")
                    .append(code(obligation.capability)).append(" | [#").append(obligation.slice)
                    .append("](https://github.com/zerocloud-sdk/folio-pdf/issues/").append(obligation.slice)
                    .append(") | ").append(readiness.blockers.get(obligation.id).isEmpty()
                            ? (readiness.global.isEmpty() ? "satisfied" : "blocked by release evidence") : "blocked")
                    .append(" |\n");
        }
        text.append('\n');
        for (FoundationInventory.Obligation obligation : foundation.obligations.values()) {
            text.append("<a id=\"").append(obligation.id).append("\"></a>\n### ").append(code(obligation.id)).append("\n\n");
            text.append(escape(obligation.summary)).append("\n\n");
            text.append("- Acceptance Profile: ").append(code(obligation.profile)).append("; [contract](../../")
                    .append(obligation.profileContract).append(")\n");
            text.append("- Kind: ").append(code(obligation.kind)).append("; owner ").append(code(obligation.capability)).append('\n');
            if (!obligation.parent.isEmpty()) {
                text.append("- Aggregate capability: ").append(code(obligation.parent)).append('\n');
            }
            text.append("- Environments: ").append(list(obligation.environments)).append('\n');
            text.append("- Execution profiles: ").append(list(obligation.executions)).append('\n');
            text.append("- Mandatory chains: ").append(list(obligation.chains)).append('\n');
            text.append("- Dependencies: ").append(list(obligation.dependencies)).append('\n');
            text.append("- Aggregate members: ").append(list(obligation.members)).append('\n');
            for (FoundationInventory.FacadeFamily family : obligation.facades) {
                text.append("- Required Facade family: ").append(escape(family.name)).append(" (")
                        .append(code(family.referencePrefix)).append("); mappings: ")
                        .append(family.mappings.isEmpty() ? "**missing**" : list(family.mappings)).append('\n');
            }
            if (!obligation.nativeOnlyReason.isEmpty()) {
                text.append("- Native Interface only: ").append(escape(obligation.nativeOnlyReason)).append('\n');
            }
            text.append("- Source requirements: ");
            for (int index = 0; index < obligation.requirements.size(); index++) {
                if (index > 0) {
                    text.append(", ");
                }
                FoundationInventory.Requirement requirement = obligation.requirements.get(index);
                text.append('[').append(code(requirement.id)).append("](#").append(requirement.id).append(')');
            }
            text.append("\n\n");
            for (String error : readiness.blockers.get(obligation.id)) {
                text.append("- Blocker: ").append(escape(error.replace(repositoryPrefix, ""))).append('\n');
            }
            text.append('\n');
        }
        text.append("## Retained limitations\n\n");
        text.append("Classifications bind the exact Capability Matrix limitation text by SHA-256; changed or unclassified text fails inventory validation. ");
        text.append("A release-blocker must be resolved by its owning slice, with preserved source requirements and evidence; deleting required behavior is not a resolution.\n\n");
        Map<String, InventoryModel.Capability> capabilities = foundation.capabilities();
        for (FoundationInventory.Limitation limitation : foundation.limitations) {
            text.append("- ").append(code(limitation.capability)).append(" / ").append(code(limitation.disposition))
                    .append(" → [").append(code(limitation.obligation)).append("](#").append(limitation.obligation)
                    .append("): ").append(escape(limitation.reason)).append('\n');
            for (String original : capabilities.get(limitation.capability).limitations) {
                if (FoundationHashes.text(original).equals(limitation.sha256)) {
                    text.append("  Original limitation: ").append(escape(original)).append('\n');
                    break;
                }
            }
        }
        text.append("\n## Source requirement catalogue\n\n");
        for (FoundationInventory.Requirement requirement : foundation.requirements) {
            text.append("<a id=\"").append(requirement.id).append("\"></a>\n");
            text.append("- ").append(code(requirement.id)).append(" — ").append(escape(requirement.source)).append('\n');
            text.append("  ").append(escape(requirement.text)).append('\n');
            text.append("  Disposition: ").append(code(requirement.disposition)).append(". ")
                    .append(escape(requirement.reason)).append(" Obligations: ").append(list(requirement.obligations)).append("\n\n");
        }
        return MarkdownGenerator.finishDocument(text);
    }

    private static String list(List<String> values) {
        return values.isEmpty() ? "none" : code(String.join(", ", values));
    }

    private static String code(Object value) {
        return "`" + escape(String.valueOf(value)).replace("`", "&#96;") + "`";
    }

    private static String escape(String value) {
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("|", "&#124;")
                .replace('\n', ' ').replace('\r', ' ');
    }
}
