#Actual T11 observation
#Thu Sep 10 15:38:57 UTC 2026
external-file.unmutated=pass
inert-xinclude.pdf-sha256=a0d0fe1668097ba7d277d1dc654495e2556b21eab390257d9ad031851f5fd553
observer.file-attempts=1
external-file.file-accesses=0
external-file.code=COMMAND_REJECTED
observer.network-attempts=1
external-network.code=COMMAND_REJECTED
external-file.pdf-sha256=93b6024794e061a28439f9f1d08d32911a3eefb2656cabbb9270bea589000569
external-network.pdf-sha256=f060f2ddbab5a21f2321b520e68e8585998ccb5b83e1a77047096eacec823633
malformed.unmutated=pass
external-file.network-accesses=0
external-network.network-accesses=0
external-network.unmutated=pass
malformed.pdf-sha256=781228676bb940574067905f212cea13dc11eb12f9fcc28f740acbac1eefc8ad
result=pass
inert-xinclude.exact=pass
api=native
inert-xinclude.reopened=pass
malformed.reopened=pass
external-network.reopened=pass
external-file.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
external-network.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
malformed.network-accesses=0
malformed.file-accesses=0
inert-xinclude.network-accesses=0
inert-xinclude.file-accesses=0
external-network.file-accesses=0
malformed.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
execution-profile=IN_PROCESS
inert-xinclude.accepted=pass
malformed.code=COMMAND_REJECTED
external-file.reopened=pass
