#Actual independent observation
#Tue Sep 29 17:59:35 UTC 2026
execution-profile=IN_PROCESS
input-sha256=4d5e7cdd98e6e4df4ce46bc53cdc38dedf347c89a1cafc4a8931655733a9eb3c
product=uncertain-geometry
profile=T13-text-logical-structure
qualified-standard-rule-count=376
required-chains=semantic,standards,syntax
retained-files-sha256=0b0bf6af8a6d09f6c4a2054dcc853c03fbbb0e5e9ea9c6474d6b77679699d74c
semantic=pass
standards=pass
syntax=pass
visual=not-required
