#Actual T10 observation
#Wed Sep 09 22:05:03 UTC 2026
semantic=pass
page.1.visual=pass
input-sha256=657cca907b0844ea6ff80f41b8326def571a1e5c47e928296cf5e61f042b2448
page.2.visual=pass
profile=T10-page-manipulation-merge-split
standards-rule-count=84
semantic-scope=frozen-corpus
standards=pass
page.4.visual=pass
syntax=pass
visual=pass
page.3.visual=pass
page.5.visual=pass
page-count=5
execution-profile=IN_PROCESS
