#Actual independent observation
#Sun Oct 04 21:49:57 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=embedded-font-kinds
required-chains=semantic,standards,syntax,visual
input-sha256=42739ab6a69bad744268186e2c51969df0378b78e2a8be228b88cef3025438a2
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=76ce33ca04751b0ce4e62fef743012d9620ba799257e02d8cb59d0d62a6fd6c2
execution-profile=IN_PROCESS
