#Actual independent observation
#Sun Oct 04 21:59:26 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=nested-split-type3
required-chains=semantic,standards,syntax,visual
input-sha256=9eb365ec07fac866952b22949a7debb242ebbdb46d3150b420348b59a624f009
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=cf2a00275e61294d28a553297db3f8462bc74d439e93f2a23e0123144de91093
execution-profile=HARDENED_WORKER
