#Actual T11 observation
#Sun Oct 04 18:34:20 UTC 2026
phase=certification
native-execution-profile=IN_PROCESS
facade-execution-profile=IN_PROCESS
profile=T11-metadata-outlines-destinations-attachments
