#Actual T11 observation
#Fri Oct 02 01:38:12 UTC 2026
external-file.unmutated=pass
inert-xinclude.pdf-sha256=ac24e5e3f90322fad636c174d8db106cb385d8adcd8409eedc5131cab4e54309
observer.file-attempts=1
external-file.file-accesses=0
external-file.code=COMMAND_REJECTED
observer.network-attempts=1
external-network.code=COMMAND_REJECTED
external-file.pdf-sha256=d41c751b58cf4c48d878fe3ab76ece6f7dbd6fa7926cf6ee3eab739cd51e036b
external-network.pdf-sha256=871caa987de7d2e4b3ea3c1eefe64af16fa12debb0816a265d6d06aa55c6a2af
malformed.unmutated=pass
external-file.network-accesses=0
external-network.network-accesses=0
external-network.unmutated=pass
malformed.pdf-sha256=27ce70180039a7b591007a77d2252dd4448e936ccdeb5bb022f1a45b43d78af3
result=pass
inert-xinclude.exact=pass
api=native
inert-xinclude.reopened=pass
malformed.reopened=pass
external-network.reopened=pass
external-file.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
external-network.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
malformed.network-accesses=0
malformed.file-accesses=0
inert-xinclude.network-accesses=0
inert-xinclude.file-accesses=0
external-network.file-accesses=0
malformed.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
execution-profile=IN_PROCESS
inert-xinclude.accepted=pass
malformed.code=COMMAND_REJECTED
external-file.reopened=pass
