#Actual T11 observation
#Sun Sep 13 21:53:20 UTC 2026
result=pass
native-execution-profile=HARDENED_WORKER
native=pass
facade-execution-profile=IN_PROCESS
profile=T11-metadata-outlines-destinations-attachments
facade=pass
signed=pass
