#Actual independent observation
#Mon Sep 28 23:51:52 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=uncertain-geometry
required-chains=semantic,standards,syntax
input-sha256=4d5e7cdd98e6e4df4ce46bc53cdc38dedf347c89a1cafc4a8931655733a9eb3c
profile=T13-text-logical-structure
syntax=pass
visual=not-required
retained-files-sha256=b34c011a48244c66dd6f6c9f86444689ce365cb7811a695c5aa8da0cf564eda9
execution-profile=IN_PROCESS
