#Actual T11 observation
#Thu Sep 10 15:45:59 UTC 2026
malformed.unmutated=pass
malformed.reopened=pass
malformed.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
inert-xinclude.pdf-sha256=a193deee3153127046a33aff9f27c968e8569a5e85a97bbe8571abea27312e81
malformed.pdf-sha256=8f4d3f1312fa2715209ac1dde7976014b1afbc5267768587a5d25f0d9b94d099
external-file.unmutated=pass
malformed.code=COMMAND_REJECTED
external-network.pdf-sha256=7eb527e2bc56a7177d85a2334f57a497eaea6a7fca00afe6e41dfc604137a4e3
inert-xinclude.accepted=pass
observer.network-attempts=1
external-network.code=COMMAND_REJECTED
inert-xinclude.exact=pass
result=pass
external-network.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
inert-xinclude.network-accesses=0
external-file.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
inert-xinclude.file-accesses=0
external-network.reopened=pass
api=native
malformed.file-accesses=0
observer.file-attempts=1
external-file.pdf-sha256=6357729c19cdb8d37b08edf9410fdedf2bc6a6250fd355c81a9995fe03ebcef5
external-file.file-accesses=0
external-file.network-accesses=0
inert-xinclude.reopened=pass
malformed.network-accesses=0
external-file.code=COMMAND_REJECTED
external-network.unmutated=pass
external-network.file-accesses=0
external-network.network-accesses=0
external-file.reopened=pass
execution-profile=IN_PROCESS
