#Policy qualification; this JVM is not the production Worker
#Tue Oct 06 21:05:55 UTC 2026
denied-hard-link=pass
permitted-symbolic-link=pass
permitted-hard-link=pass
denied-unix-listen=api-unavailable
denied-unix-permission=pass
unix-java-api=unavailable
installed-manager=net.zerocloud.pdf.HardenedWorkerSecurityManager
denied-symbolic-link=pass
