#Actual T11 observation
#Fri Oct 02 01:45:17 UTC 2026
phase=certification
native-execution-profile=HARDENED_WORKER
facade-execution-profile=IN_PROCESS
profile=T11-metadata-outlines-destinations-attachments
