#Actual independent observation
#Mon Sep 28 07:19:18 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=nested-split-type3
required-chains=semantic,standards,syntax,visual
input-sha256=9eb365ec07fac866952b22949a7debb242ebbdb46d3150b420348b59a624f009
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=5c1b6f7180282075fd756480b73f9bd48136168a9bad7f9ad2c93675a634d847
execution-profile=IN_PROCESS
