#Actual independent observation
#Tue Sep 29 16:39:07 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=embedded-font-kinds
required-chains=semantic,standards,syntax,visual
input-sha256=42739ab6a69bad744268186e2c51969df0378b78e2a8be228b88cef3025438a2
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=aa8ed95f0dc100c7ceeb6bcf399c46e91359de078845e8e93028a5f64d4fd86b
execution-profile=IN_PROCESS
