#Actual T10 observation
#Thu Sep 10 16:29:33 UTC 2026
page.1.visual=pass
visual=pass
standards=pass
profile=T10-page-manipulation-merge-split
input-sha256=f3369c51504304ec52795cb4141b0b66a81cead24893a6d9e5eb3dd7c6fa689a
syntax=pass
execution-profile=IN_PROCESS
standards-rule-count=84
semantic-scope=frozen-corpus
page-count=3
page.3.visual=pass
semantic=pass
page.2.visual=pass
