#Actual independent observation
#Tue Oct 06 11:19:28 UTC 2026
execution-profile=IN_PROCESS
input-sha256=5ee1ba455b80d804eb3245ae57736cd1bcf70c4fbb980d173d8b573ffe4950d5
product=embedded-font-inheritance
profile=T13-text-logical-structure
qualified-standard-rule-count=376
required-chains=semantic,standards,syntax
retained-files-sha256=91ca4a66da92ba63da7d41e96d31de86ddc11ff5e2b0a96f8859acee7a6aae65
semantic=pass
standards=pass
syntax=pass
visual=not-required
