#Actual T11 observation
#Thu Sep 10 21:59:04 UTC 2026
execution-profile=IN_PROCESS
input-sha256=0b71b6e462db0fdfdf14471920a0affce9182d259dff9e33ac25f4ccebaad33c
page-count=2
page.1.visual=pass
page.2.visual=pass
profile=T11-metadata-outlines-destinations-attachments
semantic=pass
semantic-scope=frozen-corpus
standards=pass
standards-rule-count=170
syntax=pass
visual=pass
