#Actual independent observation
#Tue Sep 29 18:06:18 UTC 2026
execution-profile=HARDENED_WORKER
input-sha256=9eb365ec07fac866952b22949a7debb242ebbdb46d3150b420348b59a624f009
product=nested-split-type3
profile=T13-text-logical-structure
qualified-standard-rule-count=376
required-chains=semantic,standards,syntax,visual
retained-files-sha256=dc8a222364a2484e565f00b977fee550b3ee39ee638822afac416959f284e233
semantic=pass
standards=pass
syntax=pass
visual=pass
