#Actual T11 observation
#Thu Sep 10 13:31:22 UTC 2026
malformed.unmutated=pass
malformed.reopened=pass
malformed.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
inert-xinclude.pdf-sha256=ceb56675bfbf17eb4ebd33efd781a06ce1da058f5d9fa123bb8d09f06b0b3dc8
malformed.pdf-sha256=4c0db1014020c5049277bc9e3801793a4a9b8d36d3090d9e6e82889652457677
external-file.unmutated=pass
malformed.code=COMMAND_REJECTED
external-network.pdf-sha256=a92ad467013e4468b60c13fe82f0e4bba79f1b070c5fb66a0218b8b8d4131fd9
inert-xinclude.accepted=pass
observer.network-attempts=1
external-network.code=COMMAND_REJECTED
inert-xinclude.exact=pass
result=pass
external-network.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
inert-xinclude.network-accesses=0
external-file.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
inert-xinclude.file-accesses=0
external-network.reopened=pass
api=native
malformed.file-accesses=0
observer.file-attempts=1
external-file.pdf-sha256=8480c95573279a84fb397b788ec49262040b26f2cecaa576a24e33e4498a8803
external-file.file-accesses=0
external-file.network-accesses=0
inert-xinclude.reopened=pass
malformed.network-accesses=0
external-file.code=COMMAND_REJECTED
external-network.unmutated=pass
external-network.file-accesses=0
external-network.network-accesses=0
external-file.reopened=pass
execution-profile=IN_PROCESS
