#Actual T11 observation
#Mon Sep 28 04:58:20 UTC 2026
api=native
execution-profile=IN_PROCESS
external-file.code=COMMAND_REJECTED
external-file.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
external-file.file-accesses=0
external-file.network-accesses=0
external-file.pdf-sha256=47ce1c6f921f6fc2b10a4678731fb2a29c564612ac6f82ffd880948433738c8b
external-file.reopened=pass
external-file.unmutated=pass
external-network.code=COMMAND_REJECTED
external-network.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
external-network.file-accesses=0
external-network.network-accesses=0
external-network.pdf-sha256=45651a66f274b606ee87b9c332647cfc6a23159b2355867dd239204637204845
external-network.reopened=pass
external-network.unmutated=pass
inert-xinclude.accepted=pass
inert-xinclude.exact=pass
inert-xinclude.file-accesses=0
inert-xinclude.network-accesses=0
inert-xinclude.pdf-sha256=901b124704a1d50d2c869d92bae57b2f82f4709f99f087d554869532cd15db23
inert-xinclude.reopened=pass
malformed.code=COMMAND_REJECTED
malformed.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
malformed.file-accesses=0
malformed.network-accesses=0
malformed.pdf-sha256=c00777c8121121a0f405b492feb8ec3636a049b749677828f290d39fb04c6b34
malformed.reopened=pass
malformed.unmutated=pass
observer.file-attempts=1
observer.network-attempts=1
result=pass
