#Actual T11 observation
#Fri Sep 11 12:39:42 UTC 2026
malformed.unmutated=pass
malformed.reopened=pass
malformed.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
inert-xinclude.pdf-sha256=ef20a31e18d3b86dceded6edf64fd28ad98d5ba1b2c38ec82592bab93ad92458
malformed.pdf-sha256=4b85c0da8f990cb8c38444dff87cff04a55abbba816fc7ea5f99c8757ee53938
external-file.unmutated=pass
malformed.code=COMMAND_REJECTED
external-network.pdf-sha256=e6e4f3e27a66fffaae42fa20e2061237f0d3fef8dd48d312e53e2f04fe2c7fcf
inert-xinclude.accepted=pass
observer.network-attempts=1
external-network.code=COMMAND_REJECTED
inert-xinclude.exact=pass
result=pass
external-network.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
inert-xinclude.network-accesses=0
external-file.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
inert-xinclude.file-accesses=0
external-network.reopened=pass
api=native
malformed.file-accesses=0
observer.file-attempts=1
external-file.pdf-sha256=6ce25351b8b0403750a15aa030f7d7fe75342814fb85989e5b9851765abca5b5
external-file.file-accesses=0
external-file.network-accesses=0
inert-xinclude.reopened=pass
malformed.network-accesses=0
external-file.code=COMMAND_REJECTED
external-network.unmutated=pass
external-network.file-accesses=0
external-network.network-accesses=0
external-file.reopened=pass
execution-profile=IN_PROCESS
