#Actual T11 observation
#Wed Sep 30 08:07:50 UTC 2026
facade=pass
facade-execution-profile=IN_PROCESS
native=pass
native-execution-profile=IN_PROCESS
profile=T11-metadata-outlines-destinations-attachments
result=pass
signed=pass
