#Actual T11 observation
#Thu Sep 10 18:46:52 UTC 2026
facade-execution-profile=IN_PROCESS
phase=certification
profile=T11-metadata-outlines-destinations-attachments
native-execution-profile=HARDENED_WORKER
