#Actual T11 observation
#Mon Sep 28 21:37:10 UTC 2026
api=native
execution-profile=IN_PROCESS
external-file.code=COMMAND_REJECTED
external-file.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
external-file.file-accesses=0
external-file.network-accesses=0
external-file.pdf-sha256=70d7a3e4dce97edc3f00ea2e135b1f879e76ac6c0842897328e19c35c8d7e9cc
external-file.reopened=pass
external-file.unmutated=pass
external-network.code=COMMAND_REJECTED
external-network.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
external-network.file-accesses=0
external-network.network-accesses=0
external-network.pdf-sha256=b9c57ce495dec1629a857ac2e39dd36ee4ce633933d37fd685cd574aca042b0f
external-network.reopened=pass
external-network.unmutated=pass
inert-xinclude.accepted=pass
inert-xinclude.exact=pass
inert-xinclude.file-accesses=0
inert-xinclude.network-accesses=0
inert-xinclude.pdf-sha256=e346ef195974da88f41f0e3d5fe6445b3c14ba23c43800ce843ac4a749051f30
inert-xinclude.reopened=pass
malformed.code=COMMAND_REJECTED
malformed.diagnostic=The XMP packet is not a well-formed XMP metadata packet.
malformed.file-accesses=0
malformed.network-accesses=0
malformed.pdf-sha256=92d8eda7583c2ca1674eb49b6a92ad86bd11a7442712ea8985ffc9e632ef0161
malformed.reopened=pass
malformed.unmutated=pass
observer.file-attempts=1
observer.network-attempts=1
result=pass
