#Actual independent observation
#Tue Sep 29 00:04:47 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=embedded-font-kinds
required-chains=semantic,standards,syntax,visual
input-sha256=42739ab6a69bad744268186e2c51969df0378b78e2a8be228b88cef3025438a2
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=e7032dcd775a860b632d3eb2626985a1099315e0e7c5a529f5289d69c4fb56c4
execution-profile=IN_PROCESS
