#Actual independent observation
#Tue Sep 29 16:36:11 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=nested-split-type3
required-chains=semantic,standards,syntax,visual
input-sha256=9eb365ec07fac866952b22949a7debb242ebbdb46d3150b420348b59a624f009
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=015b9b25b7ae910a4e1b000557a06f7050bcbd18b9c558b3507d3dcb6d4e9518
execution-profile=IN_PROCESS
