#Actual independent observation
#Sun Oct 04 22:39:21 UTC 2026
execution-profile=HARDENED_WORKER
input-sha256=42739ab6a69bad744268186e2c51969df0378b78e2a8be228b88cef3025438a2
product=embedded-font-kinds
profile=T13-text-logical-structure
qualified-standard-rule-count=376
required-chains=semantic,standards,syntax,visual
retained-files-sha256=1f9469c5cfbaf1cc2ff0957a7986295dee610356bd9e680427a6961304f23a1a
semantic=pass
standards=pass
syntax=pass
visual=pass
