#Actual independent observation
#Mon Sep 28 07:30:11 UTC 2026
standards=pass
qualified-standard-rule-count=376
semantic=pass
product=embedded-font-kinds
required-chains=semantic,standards,syntax,visual
input-sha256=42739ab6a69bad744268186e2c51969df0378b78e2a8be228b88cef3025438a2
profile=T13-text-logical-structure
syntax=pass
visual=pass
retained-files-sha256=ab0b357d5e1d68368db2bd191a89779cf00f3c1fc47a399de3419a57a1ebbe63
execution-profile=IN_PROCESS
