#Actual independent observation
#Sun Oct 04 20:29:40 UTC 2026
visual=not-required
standards=pass
required-chains=semantic,standards,syntax
profile=T13-text-logical-structure
input-sha256=4d5e7cdd98e6e4df4ce46bc53cdc38dedf347c89a1cafc4a8931655733a9eb3c
syntax=pass
execution-profile=HARDENED_WORKER
retained-files-sha256=3c412d427efd3d184a52cca84106730be872de56b2ea0c7a0a7a26fb2df8f0f3
qualified-standard-rule-count=376
semantic=pass
product=uncertain-geometry
